[package]
name = "lartycc-desktop-webview"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
rust-version = "1.88"
publish = false

[workspace]

[dependencies]
lartycc-desktop = { path = "../desktop" }
tao = "=0.36.0"
wry = "=0.56.1"

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
all = "deny"
pedantic = "warn"
