[package]
name = "lartycc-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "lartycc"
path = "src/main.rs"

[dependencies]
lartycc-audio-bridge = { path = "../../audio-bridge" }
lartycc-core = { path = "../../core" }

[lints]
workspace = true
